[atom]
format = "cson"
file = "louk.cson"
previewDir = "../../.atom/packages/language-louk/"
distDir = "../language-louk/"
grammarSubdir = "grammars/"

[sublime]
format = "plist"
file = "louk.tmLanguage"
previewDir = "../../Library/Application Support/Sublime Text 3/Packages/User/"
distDir = "../louk-syntax/"
grammarSubdir = ""
