[atom]
format = "cson"
previewDir = "../../.atom/packages/language-louk/"
distDir = "../language-louk/"
grammarfile = "louk.cson"
grammarSubdir = "grammars/"
settingsFile = "language-atom.cson"
settingsSubdir = "settings/"

[sublime]
format = "plist"
previewDir = "../../Library/Application Support/Sublime Text 3/Packages/User/"
distDir = "../louk-syntax/"
grammarFile = "louk.tmLanguage"
grammarSubdir = ""
