[atom]
format = "cson"
previewDir = "../../.atom/packages/language-louk/"
distDir = "../louk-editor-atom/"
grammarFile = "louk.cson"
grammarSubdir = "grammars/"
settingsFile = "language-atom.cson"
settingsSubdir = "settings/"
bundle = ""

[sublime]
format = "plist"
previewDir = "../../Library/Application Support/Sublime Text 3/Packages/User/"
distDir = "../louk-editor-sublime/"
grammarFile = "louk.tmLanguage"
grammarSubdir = ""
settingsFile = "Settings.tmPreferences"
settingsSubdir = ""
bundle = ""

[textmate]
format = "plist"
previewDir = "../../Library/Application Support/TextMate/Bundles"
distDir = "../louk-editor-textmate/"
grammarFile = "louk.tmLanguage"
grammarSubdir = "Syntaxes/"
bundle = "Louk.tmbundle"
