# Options
# format: Serial data format for grammar and settings output
# previewDir: Directory for previewing the bundle on your development machine
# distDir: Directory for bundle distribution
# grammarFile: File name for grammar output
# grammarSubdir: Subdirectory for grammar file in bundle, if applicable
# settingsFile: File name for settings output
# settingsSubDir: Subdirectory for settings file in bundle, if applicable
# bundle: Name of zipped archive for bundle, if applicable

[atom]
format = "cson"
previewDir = "../../.atom/packages/language-louk/"
distDir = "../louk-editor-atom/"
grammarFile = "louk.cson"
grammarSubdir = "grammars/"
settingsFile = "language-atom.cson"
settingsSubdir = "settings/"

[sublime]
format = "plist"
previewDir = "../../Library/Application Support/Sublime Text 3/Packages/User/Louk"
distDir = "../louk-editor-sublime/"
grammarFile = "Louk.tmLanguage"
settingsFile = "Settings.tmPreferences"

[vscode]
format = "json"
previewDir = "../../.vscode/extensions/louk/"
distDir = "../louk-editor-vscode/"
grammarFile = "louk.tmLanguage.json"
grammarSubdir = "syntaxes/"
settingsFile = "language-configuration.json"

[textmate]
format = "plist"
previewDir = "../../Library/Application Support/TextMate/Bundles"
distDir = "../louk-editor-textmate/"
grammarFile = "louk.tmLanguage"
grammarSubdir = "Syntaxes/"
bundle = "Louk.tmbundle"
