[atom]
format = "cson"
previewDir = "../../.atom/packages/language-louk/"
distDir = "../louk-editor-atom/"
grammarFile = "louk.cson"
grammarSubdir = "grammars/"
settingsFile = "language-atom.cson"
settingsSubdir = "settings/"

[sublime]
format = "plist"
previewDir = "../../Library/Application Support/Sublime Text 3/Packages/User/Louk"
distDir = "../louk-editor-sublime/"
grammarFile = "Louk.tmLanguage"
grammarSubdir = ""
settingsFile = "Settings.tmPreferences"
settingsSubdir = ""

[vscode]
format = "json"
previewDir = "../../Desktop"
distDir = "../louk-editor-vscode/"
grammarFile = "louk.tmLanguage.json"
grammarSubdir = "syntaxes/"
settingsFile = "language-settings.tmPreferences"
settingsSubdir = ""

[textmate]
format = "plist"
previewDir = "../../Library/Application Support/TextMate/Bundles"
distDir = "../louk-editor-textmate/"
grammarFile = "louk.tmLanguage"
grammarSubdir = "Syntaxes/"
bundle = "Louk.tmbundle"
