---
"*": ""
atom:
  .text.html.vue.louk:
    editor:
      commentStart: "// "
sublime:
  name: Comments
  scope: text.html.vue.louk
  settings:
    shellVariables:
      - name: TM_COMMENT_START
        value: //
