---
atom:
  .text.html.vue.louk:
    editor:
      commentStart: "// "
sublime:
  name: Comments
  scope: text.html.vue.louk
  settings:
    shellVariables:
      - name: TM_COMMENT_START
        value: //
vscode:
  contributes:
    languages:
    - id: markdown
    grammars:
    - language: markdown
      scopeName: text.html.vue.louk
      path: ./syntaxes/louk.tmLanguage.json
